spring:
  datasource:
    username: root
    password: loveless
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  type-aliases-package: com.atduu.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    com.atduu: info
  file:
    name: log/blog-pro.log

server:
  port: 8081